#%RAML 1.0
title: hola
/top:
    get:
        description: "get something"
        queryParameters:
            number:
                type: number
                required: true
            string:
                type: string
                required: false
            object:
                type: object
                properties:
                    uno:
                        type: string
                        required: false
