#%RAML 1.0
title: api title
version: v1
baseUri: http://base.uri
mediaType: application/json
protocols: [HTTP, HTTPS]

documentation:
    - title: doc title 1
      content: single line
    - title: doc title 2
      content: |
           multi
           line

types:
    User:
        type: object
        properties:
            firstname: string
            lastname: string
            age: number

traits:
    one:
        displayName: uno
        description: method description
    two:
        displayName: dos

resourceTypes:
    first:
        usage: first usage

/top:
    description: top description
    type: first
    get:
        description: get something
    post:
        description: post something
        body: &bodyPost
            application/json:
                type: User
                example: |
                    {
                        "firstname": "tato",
                        "lastname": "bores",
                        "age": 66
                    }
            application/xml:
                type: User
        responses:
            200:
                body: *bodyPost
            400:


    /child:
        description: child description
