#%RAML 1.0
title: hola
mediaType: application/json

traits:
    one:
        displayName: uno
        description: method description
    two:
        displayName: dos

/top:
    get:
        description: "get something"
