#%RAML 1.0
title: API with Examples
types:
  User:
    type: !include xsd-includer.xsd
    examples:
      - <Person>
            <firstName>Bob</firstName>
            <lastName>Marley</lastName>
            <age>ten</age>
        </Person>
      - <Person>
            <firstName>Donald</firstName>
            <lastName>Trump</lastName>
            <age>1000</age>
        </Person>
